{% set name = "pycgtool" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycgtool-{{ version }}.tar.gz
  sha256: 308ce3ac6a2bd3d37d397cf47d5e5defc518754012eb757d3a7d46a8776c3826

build:
  number: 3
  skip: true  # [py>=40 or py2k]
  entry_points:
    - pycgtool = pycgtool.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - poetry
  run:
    - astunparse ==1.6.2
    - mdtraj >=1.9.5,<2.0.0,!=1.9.6
    - numpy >=1.19.1,<2.0.0  # [py<37]
    - python
    - rich >=9.2.0,<10.0.0
    - wheel >=0.35.1,<0.36.0

test:
  imports:
    - pycgtool
    - pycgtool.parsers
  commands:
    - pycgtool --help

about:
  home: https://github.com/jag1g13/pycgtool
  summary: Generate coarse-grained molecular dynamics models from atomistic trajectories.
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    PyCGTOOL is a tool to aid in parametrising coarse-grained (CG) molecular mechanics
    models of small molecules, for example for simulations using the popular MARTINI model.
    It generates coarse-grained model parameters from atomistic simulation trajectories
    using a user-provided mapping. Equilibrium values and force constants of bonded terms
    are calculated by Boltzmann Inversion of bond distributions collected from the input trajectory.
  doc_url: https://pycgtool.readthedocs.io/en/main/
  dev_url: https://github.com/jag1g13/pycgtool

extra:
  recipe-maintainers:
    - jag1g13
